Clic 35 sale by company report graph
whagan/custom_addons pull request #45
Opened 2020-11-08 21:09 UTC by kevinmurphy5

TASK OUTCOME

Task was completed as required by the corresponding issue.

As user, update **Custom Reports**. Go to Custom Reports -> **Custom Reports** (navbar) -> **Sales by Company**. Should be redirected to **Sales by Company**. Create a new Sales by Company Report by entering start date, end date, and selecting company.

On save, user should be able to view a pivot table with the sales for that company within the time range. As well as the newly added graphical representation of the data.

2020-11-08 21:27 UTC, whagan approved these changes
In a later merge, add demo data for company sales. Code works. Current merge approved.

2020-11-09 02:57 UTC, chang3d requested changes
check the _getcolors function

2020-11-09 02:57 UTC, chang3d commented on custom_reports/static/src/js/sales_by_company_graph.js
> +        _getColors: function(length)    {
This has a similar problem as #50. There will limit the number of elements you can graph to 7.

2020-11-09 03:55 UTC, whagan commented
Fixed issue on _getColors. Originally a mistake on my end. Credit @chang3d for catch and fix.

2020-11-10 01:52 UTC, jsalajka approved these changes
Tested and approved

2020-11-10 02:05 UTC, jsalajka approved these changes

2020-11-10 02:14 UTC, jsalajka approved these changes

2020-11-10 02:42 UTC, chang3d approved these changes

2020-11-10 02:43 UTC, merged